spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    postgresql: //postgres:spJYVTkil2srhsDO9OOi@containers-us-west-20.railway.app:6401/railway
    # url: jdbc:postgresql://localhost:5432/remix
    username: postgres
    password: spJYVTkil2srhsDO9OOi
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties: 
      hibernate:
        formate_sql: true
        enable_lazy_load_no_trans: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web: DEBUG