spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/remix
    username: postgres
    password: Xava0199
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties: 
      hibernate:
        formate_sql: true
        enable_lazy_load_no_trans: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web: DEBUG